#!/bin/sh
### BEGIN INIT INFO
# Provides:          skeleton
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO

ORACLE_BASE=/db
ORACLE_HOME=$ORACLE_BASE/home
ORACLE_BIN=$ORACLE_HOME/bin
ORACLE_OWNR=oracle

NAME=oracledb
SCRIPTNAME=/etc/init.d/$NAME

case "$1" in
  start)
	echo -n "Starting Oracle: "
	su $ORACLE_OWNR -c "$ORACLE_BIN/dbstart $ORACLE_HOME"
	touch /var/lock/oracle
	echo "OK"
	;;
  stop)
	echo -n "Shutdown Oracle: "
	su $ORACLE_OWNR -c "$ORACLE_BIN/dbshut $ORACLE_HOME"
	rm -f /var/lock/oracle
	echo "OK"
	;;
  restart)
	$SCRIPTNAME stop
	$SCRIPTNAME start
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
	exit 3
	;;
esac

:
